### ISSUE TITLE
CSS file has merge prompts left in code

### ISSUE THREAD

**Issue by onwordi** [fac-15/hungryish-app#30]
Hey, some merge prompt text was left in the code. Would be best to remove them :)

<img width="463" alt="screen shot 2018-11-16 at 10 21 48" src="https://user-images.githubusercontent.com/38128436/48615901-07c66000-e98a-11e8-9395-4718d73ef6a0.png">

**Comment by onwordi** [comment]
If you remove them the css styles for ```button``` will work

**Comment by teenie-quaggard** [comment]
Thanks!
