### ISSUE TITLE
Some nice commit messages!

### ISSUE THREAD

**Issue by arrested-developer** [fac-15/hungryish-app#39]
`changed button font` is nice and descriptive
`Apply aria labels for a11y` is too :)

`css stuff` is less so...

Aim for your commit message to make it really clear what changes are in that commit. It makes it much much easier when you need to go back through your commit history and track down a bug.

Also, good practice for writing commit messages is to use the imperative, e.g:

`update Readme.md`

rather than `updates` or `updated`

**Comment by Oliversw** [comment]
Thanks Michael, that's super helpful!
