### ISSUE TITLE
JS Bits

### ISSUE THREAD

**Issue by martinbagshaw** [fac-15/hungryish-app#41]
A few thoughts and whatnot:

- Would be good to used either ES6 or old style js. You can set your js to strict mode by using:
```"use strict";```. This should flag up things just as reassignment of values to ```const``` variables
- At a glance, it looks like you could use ```const```for pretty much everything in your main.js file. Give it a whirl!
 - Separation of concerns might be nice/ good practice, but take a while. It confuses me enough at the moment, I just copied the todo list structure!
 - It might be easier to organise things if you use more variables to store repeated things, for example:

```
document.getElementById("movie_name").textContent = movies.results[randomMovie].title;
```

would become

```
const movieName = document.getElementById("movie_name");
const movieRandom = movies.results[randomMovie];
movieName.textContent = movieRandom.title;
```

**Comment by boi87** [comment]
Good shout. Thanks very much!

**Comment by Oliversw** [comment]
Especially love the "use strict" and const suggestions! Thank you!!
