### ISSUE TITLE
Consider creating a random number generator function 

### ISSUE THREAD

**Issue by zurda** [fac-15/hungryish-app#43]
You're generating random numbers multiple times in your app, which is awesome and makes everything really fun :) 
Looking at your code, you might consider creating a function the takes care of that for you, giving an argument of a maximum and minimum value. This might help maintaining readability and maintainability 

From `main.js`:

```
var randomRecipe = Math.floor(Math.random() * 10);
var randomPageRecipe = Math.floor(Math.random() * 100);
```

```
    const randomGIF = Math.floor(Math.random() * 24);
```

```
  const randomNumGen = max => Math.floor(Math.random() * Math.floor(max));
```

**Comment by Oliversw** [comment]
The perils of working in groups! Fixed it now, thanks!
